import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  mainSidebar: [{type: 'autogenerated', dirName: '.'}],
  appsSidebar: [{type: 'autogenerated', dirName: 'apps'}],
  cavingSidebar: [{type: 'autogenerated', dirName: 'apps/caving'}],
  dmSidebar: [{type: 'autogenerated', dirName: 'apps/damage-mapping'}],
  inspecionsSidebar: [{type: 'autogenerated', dirName: 'apps/inspections'}],
  instSidebar: [{type: 'autogenerated', dirName: 'apps/instrumentation'}],
  numModSidebar: [{type: 'autogenerated', dirName: 'apps/numerical-modelling'}],
  pasteSidebar: [{type: 'autogenerated', dirName: 'apps/paste'}],
  seismicitySidebar: [{type: 'autogenerated', dirName: 'apps/seismic'}],
  srSidebar: [{type: 'autogenerated', dirName: 'apps/stope'}],
  smSidebar: [{type: 'autogenerated', dirName: 'apps/surface-monitoring'}],
  utilSidebar: [{type: 'autogenerated', dirName: 'apps/utilities'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
